### ISSUE TITLE
Identity Loss

### ISSUE THREAD

**Issue by mhusseinsh** [mingyuliutw/UNIT#100]
Hello,

One of the interesting parts in the CycleGAN implementation is the identity loss, which ensures that the network should act as an identity mapping not translation in case if it is fed from a real sample from the target domain.
Example:
Snow to Summer translation
if the network is fed with Snow, it should output a summer image
if it is fed with a summer image, "using the same Encoder-Decoder for the Snow2Summer", it should output the exact identical summer image with no translation

I wonder, if the UNIT is able to handle such scenario, or if there is something similar to the identity loss is implemented.

**Comment by mingyuliutw** [comment]
The Cycle Consistency loss is not always desirable in my experiences. But yes, we have the cycle consistency loss in our implementation, which can be enabled by setting the weights to non-zero. Please check the example yaml file.
