### ISSUE TITLE
Importance of data augmentation

### ISSUE THREAD

**Issue by sanchitsgupta** [mingyuliutw/UNIT#104]
Hi,

I am working with translating images from the gta domain to the cityscapes one. I observed that you have incorporated data augmentation in your model in the form of horizontal flips and random crops. My doubt was that since we are training UNIT in order to translate full size images from one domain to the other, wouldn't it be better to show UNIT full size images while training (in contrast to random crops).

While carrying out your experiments, did you gather any empirical evidence of the importance of data augmentation, specifically the random crops?

Also I am relatively new to the field of image-to-image translation, so it would be great if you could share your insights on this matter, like the intuitive/theoretical reasons for using random crops and not showing UNIT a full image at a time.

Thank you :)

**Comment by mingyuliutw** [comment]
Sorry for the late reply, random cropping smooth out the data distribution. In my opinion, it makes overlapping of source and target domain distributions easier.
