### ISSUE TITLE
Conversion from visual images to infrared images

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [mingyuliutw/UNIT#111]
Hi Sir, 
         I want to convert visual images to infrared images for my project.  I have paired infrared - visible images for training. (FLIR dataset and Kaist Dataset). Is it possible to do this task using this repo?

**Comment by mingyuliutw** [comment]
It is possible.

The updated UNIT implementation is available at 

https://github.com/NVlabs/imaginaire

Support should be better there.
