### ISSUE TITLE
NotFoundError: NewRandomAccessFile failed to Create/Open: images/labelmap.pbtxt : The system cannot find the file specified; No such file or directory

### ISSUE THREAD

**Issue by DanielAcosta11** [mingyuliutw/UNIT#118]
![Screen Shot 2021-09-18 at 8 18 19 PM](https://user-images.githubusercontent.com/69585784/133911619-29acee26-c184-4ad9-b158-e1f67704c456.png)

OK, so I followed this tutorial to the T: https://www.youtube.com/watch?v=a1br6gW-8Ss&t=157s. And then I get this random error. Everything was fine, I used labelImg, I generated the tfrecords, I downloaded all the software, I organized the files and extracted all the files. I'm using an up to date version of tensorflow. And the images/labelmap.pbtxt exists in the images folder (maniacal laughter). Why can't it find this file? I added a path, that still doesn't work.

**Comment by mingyuliutw** [comment]
We have moved our codebase to https://github.com/NVlabs/imaginaire
The new codebase is more up-to-date and robust.
