### ISSUE TITLE
Choosing Instance normalization instead of Batch normalization

### ISSUE THREAD

**Issue by lifelongeek** [mingyuliutw/UNIT#15]
1. Is there any reason (either empirical or theoretical) to choose Instance normalization instead of Batch normalization? The paper refer 'resnet' paper for explaining RESBLK but I think 'resnet' does not have instance normalization layer by default.

2. Additionally, is there any reason to choose RESBLK only in few layers of encoder & decoder?

**Comment by mingyuliutw** [comment]
@gmkim90 Thanks for your interest on our work. 

For Question 1, we use one sample per mini-batch. Batch Norm does not make much sense in this case. We tried not using any normalization layer but figured out using InstantNorm works a bit better visually.

For Question 2, RESBLK is used for its nice feature of increasing receptive field size without reducing the image resolution as the stride convoltuon layer would do. Each time we avoid such resolution reducing, we avoid adding one more transposed convolutional layer, which is artifact-prone. An alternative of using RESBLK is to use a UNET (autoencoders with skip connections).

**Comment by lifelongeek** [comment]
Thanks for your reply.
Why transposed convolution is artifact-prone? 
Could you provide any related work or brief comment?
I could find 'checkboard artifact' (https://arxiv.org/ftp/arxiv/papers/1707/1707.02937.pdf)

**Comment by mingyuliutw** [comment]
I will refer you to this article. https://distill.pub/2016/deconv-checkerboard/
