### ISSUE TITLE
Some questions about the paper and results

### ISSUE THREAD

**Issue by zzw1123** [mingyuliutw/UNIT#16]
Hi,mingyuliu,thanks for your contribution which inspires me a lot!
But I have one question that during translation,whether CNN detects the facial marks/features of the image and just inpaint the color and texture to the target domain while preserving the outline of the original image?
The image below shows that when transfering from a cat to a tiger,ont only the facial features are changed ,but also the face becomes bigger,so can you tell me the reason?
![image](https://user-images.githubusercontent.com/16879220/32206479-440c2b98-be30-11e7-9d7f-596bcde01e51.png)

**Comment by mingyuliutw** [comment]
For image to image translation, CNN does not need to preserve the outline of the original image. The task is to generate a translated image that is related to the input image. Most of the house cats have short noses, while tigers have longer noses hence the mapping would not be able to keep the same eye to nose distance.
