### ISSUE TITLE
Snowy2Summery model training 

### ISSUE THREAD

**Issue by ivanhoCP** [mingyuliutw/UNIT#18]
Hi MingYu,

Instead of training celeba (face attributes dataset), I would like to test Snowy2Summery.
May I know whether I need to find a whole lot of snow images if I would like to train that model myself?

Thank you very much

**Comment by mingyuliutw** [comment]
I guess YouTube could be a good data source for the task.

**Comment by ivanhoCP** [comment]
May I know how many images you used for day to night and summery to snowy?

**Comment by mingyuliutw** [comment]
Sure, it is written in the paper. https://arxiv.org/pdf/1703.00848.pdf
The numbers of the images in the sunny/day, rainy, night, summery, and snowy sets are 86165, 28915,
36280, 6838, and 6044.
