### ISSUE TITLE
The svhn mnist examples

### ISSUE THREAD

**Issue by whobefore** [mingyuliutw/UNIT#2]
Could you please provide the source code of domain adaption from svhn to mnist? I guess there are some differences with the trick training face attribute transformation or other tasks. Thanks very much!

**Comment by mingyuliutw** [comment]
Sure! Will put it online in a couple of days.

**Comment by whobefore** [comment]
It's so kind of you. Looking forward to it. :-)

**Comment by mingyuliutw** [comment]
Took sometime to migrate the old version to the release version and verify the performance. 
By executing 
cd src
python train_domain_adaptation.py --config ../exps/covaegan/da_svhn2mnist.yaml
and wait for a couple of days.
You should be able to get the performance reported in the paper.
