### ISSUE TITLE
Question about discriminator performance with weights tied for domain adaptation

### ISSUE THREAD

**Issue by gunshi** [mingyuliutw/UNIT#20]
Hi,
I had a question about how tying the weights affects the discriminator's ability to differentiate between domains when training for domain adaptation (training source domain's discriminator with target and source weights tied for higher layers, and also minimizing l1 loss between features output by them).
Intuitively it feels like that will prevent the discriminators from being good at telling the domains apart and seems counterproductive to the adversarial part of the training (even though it may be helpful for extracting similar features from two domains to get similar results on whatever task is being performed at the end of it all)? 
Just wanted to ask why this is not true(or if this is true)?
Thanks!

**Comment by mingyuliutw** [comment]
In GAN training, discriminators win all the time, even in the case of weight typing. Hence, I think trading the discriminator capacity for extracting similar features (an inductive bias) is a good deal. Without weight tying, the domain adaptation performance becomes unsatisfactory.

**Comment by gunshi** [comment]
Got it, thanks for the explanation!
