### ISSUE TITLE
day2night data

### ISSUE THREAD

**Issue by cuimiao187561** [mingyuliutw/UNIT#21]
hello mingyuliu's teacher
When I saw your essay, I was very interested. I now use Cycle gan to train from day to night translation, but my day2night data werehave limited . Can you share your data with me? My email is: cuimiao188@163.com

thank you very much

**Comment by mingyuliutw** [comment]
Thanks for your interest. The Day-time and Night-time video sequences belong to NVIDIA product teams. We are not authorized to share the data.

**Comment by cuimiao187561** [comment]
thank you @mingyuliutw
