### ISSUE TITLE
IR/RGB conversion weights

### ISSUE THREAD

**Issue by xjoshramos** [mingyuliutw/UNIT#24]
Is there a pre-trained model for converting rgb to ir and ir to rgb like mentioned in the paper?

**Comment by mingyuliutw** [comment]
We didn’t mention about IR2RGB in our NIPS paper.

**Comment by xjoshramos** [comment]
https://arxiv.org/pdf/1703.00848v1.pdf

**Comment by galsk87** [comment]
can you share the configuration for this task?
