### ISSUE TITLE
No module named 'net_config'

### ISSUE THREAD

**Issue by chikiuso** [mingyuliutw/UNIT#30]
Hi, I tried to run the training with CelebA dataset, and got the following error when I started train : 

Traceback (most recent call last):
  File "cocogan_train.py", line 6, in <module>
    from tools import *
  File "/home/paperspace/Downloads/UNIT/src/tools/__init__.py", line 6, in <module>
    from net_config import *
ModuleNotFoundError: No module named 'net_config'

Do you have any hints I could solve it? thanks!

**Comment by mingyuliutw** [comment]
@chikiuso I think you didn't set up the path correctly.

**Comment by MartinMeliss** [comment]
I was helped by the use of Python 2.7

**Comment by mingyuliutw** [comment]
I think this is due to the difference between Python 2 and Python 3. The entire code base was developed using Python 2 and I believe that you were using Python 3. I guess this can be fixed following https://stackoverflow.com/questions/12172791/changes-in-import-statement-python3

**Comment by chikiuso** [comment]
@mingyuliutw I just switched the conda to python 2 and work really well, thanks for your and Nvidia great work!

**Comment by mingyuliutw** [comment]
@chikiuso Thanks. I will be adding the multi-scale discriminators that we reported in our pix2pixHD work to this repo. Hope this could better stabilize the training.
