### ISSUE TITLE
Inverted colors

### ISSUE THREAD

**Issue by MartinMeliss** [mingyuliutw/UNIT#32]
Probably worth mentioning that sometimes the images are obtained with inverted colors, the same behavior of the network I observed in the CycleGAN. Helps restart the training.

**Comment by mingyuliutw** [comment]
@MartinMeliss Color inversion is one common failure mode for unsupervised image translation. Sometimes, it goes away when train for more iterations but sometimes it does not. I recently added multi-scale discriminator support to the code. Hope this can reduce the chance that you see color inverted.
