### ISSUE TITLE
Could it work with face rotation?

### ISSUE THREAD

**Issue by chikiuso** [mingyuliutw/UNIT#40]
Hi Ming Yu,

  I see the cat2tiger samples having cat and tiger facing left / right, does that mean this project work with the face rotation by itself? No need to annotate or list which cat image facing left, which cat image facing right? Thanks!

Best Wishes,
Chi Kiu SO

**Comment by mingyuliutw** [comment]
@chikiuso Yes, unsupervised image-to-image translation is about learning an image translation function from two sets of images, one from each domain. In the cat2tiger example, the two sets of images are a set of cat portrait images and a set of tiger portrait images. No pose info for each set is needed.
