### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by redhat12345** [mingyuliutw/UNIT#44]
I am getting low accuracy. May I know why ?

$python cocogan_train_domain_adaptation.py --config ../exps/unit/svhn2mnist.yaml --log ../logs

Iteration: 00000010/00200000
Iteration: 00000020/00200000
Iteration: 00000030/00200000
Iteration: 00000040/00200000
Iteration: 00000050/00200000
Iteration: 00000060/00200000
Iteration: 00000070/00200000
Iteration: 00000080/00200000
Iteration: 00000090/00200000
Iteration: 00000100/00200000
Classification accuracy for Test_B dataset: 0.1296
Iteration: 00000110/00200000
Iteration: 00000120/00200000
Iteration: 00000130/00200000
Iteration: 00000140/00200000
Iteration: 00000150/00200000
Iteration: 00000160/00200000
Iteration: 00000170/00200000
Iteration: 00000180/00200000
Iteration: 00000190/00200000
Iteration: 00000200/00200000
Classification accuracy for Test_B dataset: 0.1032
Iteration: 00000210/00200000
Iteration: 00000220/00200000
Iteration: 00000230/00200000
Iteration: 00000240/00200000
Iteration: 00000250/00200000
Iteration: 00000260/00200000
Iteration: 00000270/00200000
Iteration: 00000280/00200000
Iteration: 00000290/00200000
Iteration: 00000300/00200000
Classification accuracy for Test_B dataset: 0.1084
Iteration: 00000310/00200000
Iteration: 00000320/00200000
Iteration: 00000330/00200000
Iteration: 00000340/00200000
Iteration: 00000350/00200000
Iteration: 00000360/00200000
Iteration: 00000370/00200000
Iteration: 00000380/00200000
Iteration: 00000390/00200000
Iteration: 00000400/00200000
Classification accuracy for Test_B dataset: 0.0826
Iteration: 00000410/00200000
Iteration: 00000420/00200000
Iteration: 00000430/00200000
Iteration: 00000440/00200000
Iteration: 00000450/00200000
Iteration: 00000460/00200000
Iteration: 00000470/00200000
Iteration: 00000480/00200000
Iteration: 00000490/00200000
Iteration: 00000500/00200000
Classification accuracy for Test_B dataset: 0.0984
Iteration: 00000510/00200000
Iteration: 00000520/00200000
Iteration: 00000530/00200000
Iteration: 00000540/00200000
Iteration: 00000550/00200000
Iteration: 00000560/00200000
Iteration: 00000570/00200000
Iteration: 00000580/00200000
Iteration: 00000590/00200000
Iteration: 00000600/00200000
Classification accuracy for Test_B dataset: 0.0912
Iteration: 00000610/00200000
Iteration: 00000620/00200000
Iteration: 00000630/00200000
Iteration: 00000640/00200000
Iteration: 00000650/00200000
Iteration: 00000660/00200000
Iteration: 00000670/00200000
Iteration: 00000680/00200000
Iteration: 00000690/00200000
Iteration: 00000700/00200000
Classification accuracy for Test_B dataset: 0.0819

**Comment by mingyuliutw** [comment]
You just trained 700 iterations and you are expecting a good performance?

**Comment by mingyuliutw** [comment]
You just trained 700 iterations and you are expecting a good performance?

**Comment by deep0learning** [comment]
@mingyuliutw Thank you so much. May I know that after how much iteration I will get the desired results ?

**Comment by mingyuliutw** [comment]
The iteration number is written in the yaml file. It is not precise as training is a stochastic process and the loss function is non-convex.
