### ISSUE TITLE
How many epochs to get the SHVN->MNIST result?

### ISSUE THREAD

**Issue by hsm207** [mingyuliutw/UNIT#47]
In the code, the maximum epochs to train the SHVN->MNIST model is 100,000.

Do you remember what was the epoch that produced the result stated in the paper i.e. 90.53% accuracy?

**Comment by mingyuliutw** [comment]
100,000 should be the iteration numbers, not the epoch numbers. Training is a stochastic process. I can't predict which iteration gives the best result. You might not get exactly the same number, either.
