### ISSUE TITLE
Discriminator share

### ISSUE THREAD

**Issue by taki0112** [mingyuliutw/UNIT#49]
Why did not the weight of discriminators be shared?
Or maybe you tried, but the results were not good?

**Comment by mingyuliutw** [comment]
@taki0112 Thanks for your question. I found for some tasks, discriminator weight sharing is quite useful. For example, for the SVHN to MNIST domain adaptation, the two adversarial discriminators share weights for several layers. I also found that for the face image translation, discriminator weight-sharing is helpful too (The yaml file I released actually use this setting.). But when the domains are quite different and a patch-based discriminator is used, which often only have few layers. Discriminator weight sharing could hurt the performance. I am a deep believer of no free lunch theorem and am perfectly fine with using different models for different tasks. But some people prefer one model that rules all.
