### ISSUE TITLE
synthia2cityscape.yaml

### ISSUE THREAD

**Issue by can-song** [mingyuliutw/UNIT#50]
In the file ./exps/unit_local/synthia2cityscape.yaml, the sentence "root: /cosmo/datasets/cityscape_1024x512/" is error? I found that it should set as "root: ../datasets/cityscape" for "python cocogan_translate_one_image.py --config ../exps/unit_local/synthia2cityscape.yaml --a2b 0 --weights ../outputs/unit/street_scene/synthia2cityscape_gen_00250000.pkl --image_name ../images/freiburg_000000_000021_leftImg8bit.png --output_image_name ../results/synthetic_freiburg_000000_000021_leftImg8bit.png"

**Comment by mingyuliutw** [comment]
Thanks! Will fix it.

**Comment by can-song** [comment]
Can you give me the day2night datasets? Thank you !
