### ISSUE TITLE
Test time z vector representation

### ISSUE THREAD

**Issue by galsk87** [mingyuliutw/UNIT#53]
Hi I couldnt find in the paper or understand from the code what you are doing during test time in the next manner:

On train time you insert noise and you compute the mu and sd and represent z as a random vector.

What happens during test time, cause i dont see you do the same, do you use the average mu and sd or something else? i would love to know.

thanks,
Gal.

**Comment by mingyuliutw** [comment]
I do not understand your question. Please check GaussianNoiseLayer for the test time behavior.

**Comment by galsk87** [comment]
So on the test time the latent vector z is
Z=x + noise

Where x is the output of the shared layers and the noise is the
 GaussianNoiseLayer Added noise?
בתאריך יום ה׳, 25 בינו׳ 2018 ב-20:40 מאת Ming-Yu Liu-------劉洺堉 <
notifications@github.com>:

**Comment by galsk87** [comment]
Hi i tried inspecting GaussianNoiseLayer and the difference the noise would make during test time, so i multiplied the noise by a constant for example : 
  
def forward(self, x):
    if self.training == False:
      return x
    noise = Variable(torch.randn(x.size()).cuda(x.data.get_device()))
    return x + noise*10000

and did not get any impact on the result image, i also added a constant to change the mean and did not get any difference, could you please explain how did you see if at all the impact of the noise in your experiments and if not would it be reasonable to you an AE instead of VAE.

**Comment by mingyuliutw** [comment]
If you check the code that you copy-paste, you would find that in the testing the noise is not added.

**Comment by galsk87** [comment]
Did you try adding noise on test time ?
Also the noise is about 50% of the image’s power isn’t it too much?
בתאריך יום ב׳, 5 בפבר׳ 2018 ב-18:36 מאת Ming-Yu Liu-------劉洺堉 <
notifications@github.com>:

**Comment by mingyuliutw** [comment]
I did tried adding noise on the test time. I don't see much difference.
I don't know what you meant by 50% of the image's power.

**Comment by galsk87** [comment]
The average variance of the images is aroun 2 where the variance f the
noise is 1....
בתאריך יום ב׳, 5 בפבר׳ 2018 ב-19:10 מאת Ming-Yu Liu-------劉洺堉 <
notifications@github.com>:
