### ISSUE TITLE
Several Question

### ISSUE THREAD

**Issue by penincillin** [mingyuliutw/UNIT#55]
Hi, thanks for making the code public available. It is really an amazing work.
After read the paper and the source code, I have several questions.

1. In file cocogan_trainer.py, from line 73 to line 82, those member variables, self.gen_xx_loss_xx.
I only find their definition, but I haven't find where they are used. So, what's these variables for?
2. I try to train CelebA blondhair, and I find the batch size was set to 1, could the batch size be bigger than 1?
3. I find the generated image of CelebA blondhair is a little blurred. Is this phenomenon normal?

**Comment by mingyuliutw** [comment]
Batch size 1 renders the best performance for many of the datasets I tested.

Yes, you might want to adjust the loss weights to mitigate the blurry issue.
