### ISSUE TITLE
Tensorboard summary writer error

### ISSUE THREAD

**Issue by groot-1313** [mingyuliutw/UNIT#56]
I am running version_01, and I am facing problems with the summary writer. 

1. [this line ](https://github.com/mingyuliutw/UNIT/blob/version_01/src/train.py#L143) throws the following error:

> AttributeError: 'module' object has no attribute 'FileWriter'

So, I replaced it with the following line:

    train_writer = tf.summary.FileWriter("%s/%s" % (opts.log,os.path.splitext(os.path.basename(opts.config))[0]))

Upon doing so the program runs fine, until [this line](https://github.com/mingyuliutw/UNIT/blob/version_01/src/train.py#L199).

The error it throws is: 

>  in add_summary for value in summary.value:
AttributeError: 'Tensor' object has no attribute 'value'

Can anybody please point out the change I need to make.

**Comment by reborm** [comment]
Hi, I also met this error, have you solved it?

**Comment by groot-1313** [comment]
Nope, no solution yet. If you do get around it, please post it here

**Comment by lolz0r** [comment]
I also got this error. It looks like tensorboard has received an API-breaking release since this code was first written. We need to install the older version of tensorboard to make it work.

`sudo pip install 'tensorboard==1.0.0a6'
`

**Comment by mingyuliutw** [comment]
@lolz0r Thanks a lot for the info. I did not know that the tensorboard change their API. The USAGE.md page is now updated with the correct version.

**Comment by groot-1313** [comment]
Works! Thanks

**Comment by mahfujau** [comment]
I installed the 'tensorboard==1.0.0a6' version, but still getting the error. I am stacked on this. Thank you in advanced.

AttributeError: 'module' object has no attribute 'FileWriter'

**Comment by mahfujau** [comment]
Solved. Thanks.

**Comment by HusainKapadia** [comment]
This is a very basic tensorboard scalar log. 

`import numpy as np`
`import tensorflow as tf`
`a = np.arange(10)`
`x = tf.convert_to_tensor(a, dtype=tf.float32)`
`x_summ = tf.summary.scalar("X", x)`
`writer = tf.summary.FileWriter('/tmp/logdir')`
`writer.add_summary(x_summ)`

But, I get an error ` in add_summary for value in summary.value: AttributeError: 'Tensor' object has no attribute 'value'`. Any solution for this?

**Comment by hrdkjain** [comment]
try 
`writer.add_summary(x_summ).eval()`
as per the [stackoverflow answer](https://stackoverflow.com/a/47272724/5467713)

**Comment by gaceladri** [comment]
Same issue here. Not related with this library but the same problem with tensorboard. .eval() or reinstalling an older version of tensorboard have not solved my problem.

**Comment by lenovopast17** [comment]
I get the same error as well in add_summary for value in summary.value: AttributeError: 'Tensor' object has no attribute 'value'. Any solution for this?

**Comment by cottrell** [comment]
I saw there is some api change, probably to do with tf 2.0. This is working for me in tf 2.0:

train_writer = tf.summary.create_file_writer('./logs/1/train')

**Comment by teraoka-hiroshi** [comment]
Thank you

**Comment by JUNNETWORKS** [comment]
> I saw there is some api change, probably to do with tf 2.0. This is working for me in tf 2.0:
> 
> train_writer = tf.summary.create_file_writer('./logs/1/train')

This code works correctly!!
Thank you!!

**Comment by omizonly** [comment]
self.writer = tf.summary.create_file_writer(log_dir)

AttributeError: module 'tensorflow._api.v1.summary' has no attribute 'create_file_writer'

i'm using tf 1.13.1 
can anyone help me?

**Comment by quannm3110** [comment]
@omizonly 'create_file_writer' is the api for tf 2.0 while 'FileWriter' is for tf 1.x.
So you should either use 'tf.summary.FileWriter' instead.
