### ISSUE TITLE
Have you experimented with a dataset that does not have a center crop?

### ISSUE THREAD

**Issue by taki0112** [mingyuliutw/UNIT#63]
Have you experimented with a dataset that does not have a center crop?
What was the result?

When you see the results of the paper, you always have the face in the center, and the background is almost invisible.
Have you tried it in a dataset with lots of variants? For example, the conversion between a cat and a dog.

**Comment by mingyuliutw** [comment]
@taki0112 It is doable. I think you have seen the results in the [MUNIT](https://github.com/NVlabs/MUNIT) work.
