### ISSUE TITLE
I found a mistake in the code

### ISSUE THREAD

**Issue by NomotoEriko** [mingyuliutw/UNIT#66]
Dr. Ming-Yu Liu 劉洺堉

Hi. I am graduated student of Osaka University. Thanks for your great paper and open source.
I am trying to use it on my own data, but I found a mistake in file cocogan_nets.py, at line 121.
The code is written as `w = x2.size(2)`, but it seems to be `w = x2.size(3)`. 
If it doesn't have mistake can you explain it to me?

Thank you.

**Comment by mingyuliutw** [comment]
You are right. This was a mistake. This issue is fixed in the new release.
