### ISSUE TITLE
I found a mistake in the configs/*.yaml

### ISSUE THREAD

**Issue by raven38** [mingyuliutw/UNIT#70]
There aren't style_dim parameters in config files.

**Comment by mingyuliutw** [comment]
@raven38 UNIT does not require a style_dim. Just remember to specify --trainer UNIT while using the code.

**Comment by raven38** [comment]
Thank you for reply.
I see.
If I use --trainer MUNIT, it seem I need a style_dim.

**Comment by mingyuliutw** [comment]
For example of using MUNIT, please check out https://github.com/NVlabs/MUNIT

**Comment by raven38** [comment]
Thank you. I check it.
