### ISSUE TITLE
A strange result of domain adaptation

### ISSUE THREAD

**Issue by yxyuni** [mingyuliutw/UNIT#71]
Hi Mr. Liu,
I'm interested in your work and tried your code on svhn2mnist task. Here are several generated images and I want to ask why the a2b and  b2a from decode_b(ca, sb) decode_a(cb, sa) are bad?
![test_2](https://user-images.githubusercontent.com/22383353/40477254-9225edb6-5f78-11e8-8565-62df4b811a45.jpg)
![test_1](https://user-images.githubusercontent.com/22383353/40477262-96a70f6e-5f78-11e8-8048-5c0a0a5bd3d3.jpg)
But decode_b(ca, noise) decode_a(cb, noise) are good but not relavant to the original class label?
![xba](https://user-images.githubusercontent.com/22383353/40477357-d883cbe8-5f78-11e8-91b6-79047859a1e1.jpg)

![25bf23d17b036f5855d4218b416c7fdd](https://user-images.githubusercontent.com/22383353/40477333-c8eb8310-5f78-11e8-86c7-4fd4205f6eb0.png)
The first ten labels of svhn images are 8, 9, 1, 4, 3, 5, 3, 8, 5, 3 ....

**Comment by mingyuliutw** [comment]
Please check out the example code in https://github.com/mingyuliutw/UNIT/tree/version_02
for the SVHN to MNIST experiments.
