### ISSUE TITLE
Domain Adaptation Code

### ISSUE THREAD

**Issue by mahfujau** [mingyuliutw/UNIT#73]
Could you please release the code for Domain Adaptation that you mentioned in your paper?
Thanks in advanced.

**Comment by mingyuliutw** [comment]
The domain adaptation code has been made available almost for a year. Please check out the README.md. 
`05-02-2018: We now adapt MUNIT code structure. For reproducing experiment results in the NIPS paper, please check out version_02 branch.`

**Comment by mahfujau** [comment]
Thank you so much.
