### ISSUE TITLE
Run example in CPU?

### ISSUE THREAD

**Issue by BigWigs1** [mingyuliutw/UNIT#76]
Dear Sir,

I'm trying to recreate this project, but I am getting an error that says CUDA is not sufficent enough. Is there a way to run this code without having an Nvidia card. Is it possible to use your already trained models running only in the CPU? If so what part of the code would I need to change to make it run?

Many thanks for any assistance you can give.

Mohamed

**Comment by francotheengineer** [comment]
You can for sure, you'll have to edit the code in the `.cuda()` parts. But considering a P100 takes 0.5 seconds per step... you're going to be there for some time with a CPU, potentially more than a week.
