### ISSUE TITLE
Training with animal image dataset

### ISSUE THREAD

**Issue by yunjey** [mingyuliutw/UNIT#8]
@mingyuliutw Nice work! BTW, how can i get the cropped amimal face image to train your model?
I don't want to use the pretrained model. I want to train the model from scratch with the animal data. 

Thanks in advance.

**Comment by mingyuliutw** [comment]
Thanks! The animal faces were cropped from the imagenet dataset. You can run a template matching algorithm with some human supervision to get the animal faces. I am not sure if I can release the dataset.

**Comment by mingyuliutw** [comment]
I just found this cat dataset online that you might be able to use. https://web.archive.org/web/20150703060412/http://137.189.35.203/WebUI/CatDatabase/catData.html

**Comment by yunjey** [comment]
@mingyuliutw Thank you very much!
