### ISSUE TITLE
Question about the  hyper-parameters of USPS2MNIST experiment

### ISSUE THREAD

**Issue by Jie-su** [mingyuliutw/UNIT#80]
Hi,

I am a student who tries to re-implement the USPS->MNIST experiment.

Could you give the hyper-parameters of that experiment?

Thanks

**Comment by mingyuliutw** [comment]
The information you need is in README.md. 

> 05-02-2018: We now adapt MUNIT code structure. For reproducing experiment results in the NIPS paper, please check out version_02 branch.

**Comment by Jie-su** [comment]
Thanks
