### ISSUE TITLE
a question about vgg16.t7

### ISSUE THREAD

**Issue by Linlin0611** [mingyuliutw/UNIT#81]
Hello,
I downloaded the vgg16.t7 manually, when I ran"load_lua(r"D:\Progarm Files\eclipse\preferences\UNIT\vgg16.t7")",  I got this error message:"unknown type id 1056626884. The file may be corrupted."
Why is this problem? I had downloaded it several times.

Thank you for your answer.

**Comment by mingyuliutw** [comment]
@Linlin0611 Does automatic download work for you?

**Comment by Linlin0611** [comment]
@mingyuliutw  No, it doesn't work. When I ran  "os.system('wget http...')", the 'wget' seems cannot be recognized.
Thanks a lot.

**Comment by mingyuliutw** [comment]
If you are using Ubuntu, you should install wget first. Something like 

sudo apt-get install wget

**Comment by Linlin0611** [comment]
Thanks!
I am using win10, I have installed wget successfully, but it still doesn't work.

**Comment by ShihuaHuang95** [comment]
So do I... What is wrong with this weights?

**Comment by mm246** [comment]
changing line 226 of utils.py from 
vgglua = load_lua(os.path.join(model_dir, 'vgg16.t7'))
to
vgglua = load_lua(os.path.join(model_dir, 'vgg16.t7'),long_size=8)
solved the problem in my case

**Comment by 12cheny** [comment]
May you tell me where can I download vgg16.t7, I have tried many websites.

**Comment by Linlin0611** [comment]
I have one, but I'm not sure if it is what you want. 
how can I give it to you, it is more than 500M.



At 2019-03-08 16:48:38, "12cheny" <notifications@github.com> wrote:


May you tell me where can I download vgg16.t7, I have tried many websites.

**Comment by 12cheny** [comment]
It's my mail :2733743979@qq.com. You can send it to me by email. Thank you very much.

**Comment by Linlin0611** [comment]
加你好友了，邮件传递太慢了，qq上发给你




| |
戴玉静
|
|
邮箱：daiyjxyj@163.com
|

签名由 网易邮箱大师 定制

On 03/08/2019 17:03, 12cheny wrote:

It's my mail :2733743979@qq.com. You can send it to me by email. Thank you very much.

**Comment by VectNull** [comment]
Hello, have you ever encountered this problem?

for (src, dst) in zip(vgglua.parameters()[0], vgg.parameters()):
TypeError: 'NoneType' object is not callable

**Comment by BUPThua1** [comment]
> Hello, have you ever encountered this problem?
> 
> for (src, dst) in zip(vgglua.parameters()[0], vgg.parameters()): TypeError: 'NoneType' object is not callable

Hello, have you solved it?

**Comment by VectNull** [comment]
Time has passed too long, I do not seem to be able to run this network, as if this line needs to delete a parameter;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月16日(星期三) 下午3:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mingyuliutw/UNIT] a question about vgg16.t7 (#81)





  
Hello, have you ever encountered this problem?
 
for (src, dst) in zip(vgglua.parameters()[0], vgg.parameters()): TypeError: 'NoneType' object is not callable
  
Hello, have you solved it?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by VectNull** [comment]
oh,vgg16.t7 maybe translated by vgg16.weight,but it is too big,how can i give you?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mingyuliutw/UNIT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月16日(星期三) 下午3:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mingyuliutw/UNIT] a question about vgg16.t7 (#81)





  
Hello, have you ever encountered this problem?
 
for (src, dst) in zip(vgglua.parameters()[0], vgg.parameters()): TypeError: 'NoneType' object is not callable
  
Hello, have you solved it?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you commented.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

vgg16.weight (527.79M, 2022年04月21日 23:25 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=27636336162e36ed8a1df5621f63071d025100005d5757574b505a000d4e010a02564e575d54041f04050004585b50565e530155396f3544010452001714505b010b173604&code=fcc69c52

**Comment by WeiBrown** [comment]
wget http://cs.stanford.edu/people/jcjohns/fast-neural-style/models/vgg16.t7 -O 
try this

**Comment by WeiBrown** [comment]
> Hello, I downloaded the vgg16.t7 manually, when I ran"load_lua(r"D:\Progarm Files\eclipse\preferences\UNIT\vgg16.t7")", I got this error message:"unknown type id 1056626884. The file may be corrupted." Why is this problem? I had downloaded it several times.
> 
> Thank you for your answer.

wget http://cs.stanford.edu/people/jcjohns/fast-neural-style/models/vgg16.t7 -O
try this

**Comment by EXGHLI** [comment]
> > 您好，我手動下載了vgg16.t7，當我執行“load_lua(r"D:\Progarm Files\eclipse\preferences\UNIT\vgg16.t7")”時，我收到此錯誤訊息：“未知類型id ” 1056626884。文件可能已損壞。”為什麼會出現這個問題呢？我已經下載過好幾次了。
> > 謝謝您的回答。
> 
> wget http://cs.stanford.edu/people/jcjohns/fast-neural-style/models/vgg16.t7 -O 試試這個

This link seems to have expired. Is there any other way to obtain vgg16.t7?

**Comment by wylblank** [comment]
> Hello, have you ever encountered this problem?
> 
> for (src, dst) in zip(vgglua.parameters()[0], vgg.parameters()): TypeError: 'NoneType' object is not callable

您好，我也遇到了相同的问题，请问您是怎么解决的？
Hello, I also met the same problem, how did you solve it?

**Comment by wylblank** [comment]
> Time has passed too long, I do not seem to be able to run this network, as if this line needs to delete a parameter;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年3月16日(星期三) 下午3:39 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mingyuliutw/UNIT] a question about vgg16.t7 (#81) Hello, have you ever encountered this problem? for (src, dst) in zip(vgglua.parameters()[0], vgg.parameters()): TypeError: 'NoneType' object is not callable Hello, have you solved it? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

您好，或者，您可以发一下您utils.py里的第224-241行的load_vgg16()函数部分吗？我和原程序对比一下，按照您的改一下试试。谢谢
Hello, or, could you please send the load_vgg16() function section on lines 224-241 of your utils.py? Let me compare it with the original program and try to change it according to your instructions. thank you.

**Comment by wylblank** [comment]
> > Hello, have you ever encountered this problem?
> > for (src, dst) in zip(vgglua.parameters()[0], vgg.parameters()): TypeError: 'NoneType' object is not callable
> 
> Hello, have you solved it?

您好，我正在做MUNIT也遇到了相同的问题， for (src, dst) in zip(vgglua.parameters()[0], vgg.parameters()): TypeError: 'NoneType' object is not callable，请问您是怎么解决的？可以告诉我吗？谢谢
Hello, I also encountered the same problem when I was doing MUNIT, for (src, dst) in zip(vgglua.parameters()[0], vgg.parameters()): TypeError: 'NoneType' object is not callable, how did you solve it? Can you tell me? thank you.

**Comment by RahmaDivina** [comment]
hii there, i also encountered the same problem, have you solved this? i'm so frustated because i have to use it for my final project
