### ISSUE TITLE
Playing with the architecture

### ISSUE THREAD

**Issue by mhusseinsh** [mingyuliutw/UNIT#82]
Hello,
I am using the UNIT on my own dataset, but the resulting are not that satisfactory. I believe the dataset contain very complex feature classes to learn.
I though of trying to play with the architecture or hyperparameters to adapt my dataset, but I am not sure exactly from where to start ? like we already have 6 subnets with 3 main components, E, G, and D. I am not sure what can be the start, like maybe changing number of filters, or adding more layers or so. I just want to try.

Do you have any idea/recommendation from where can I start playing around ?

**Comment by mingyuliutw** [comment]
You can adjust the depth and width for each component. You could also test different loss weights. I believe the best weights and architecture for each dataset are different.
