### ISSUE TITLE
horse2zebra

### ISSUE THREAD

**Issue by caogule** [mingyuliutw/UNIT#85]
我想请教一下，unit模型如何跑马和斑马的数据集？

**Comment by mingyuliutw** [comment]
I think you could 
1. Download the imagenet dataset. 
2. Find the horse and zebra classes. (If you have a detector to get the bounding boxes of the animals, it would be the best.)
3. Modify the [unit_summer2winter_yosemite256_folder.yaml](https://github.com/mingyuliutw/UNIT/blob/master/configs/unit_summer2winter_yosemite256_folder.yaml) accordingly by setting the correct file path.
