### ISSUE TITLE
Question on Shared Weights Implementation?

### ISSUE THREAD

**Issue by truongthanhdat** [mingyuliutw/UNIT#86]
The paper showed that weights of the last few layers of encoders and first few layers of decoders are shared. However, I have not found its implementations in the source code. It seems to be that two encoders (two decoders) use separate weights.

Maybe my limitation knowledge in Pytorch library makes me do not know where is the implementation of shared weights. Can you please indicate the implementation of shared weights constraint?

Thank you very much.

**Comment by mingyuliutw** [comment]
Please check the README.md for the code branch for getting the network used to produce the results in the NIPS paper.

**Comment by zEttOn86** [comment]
@truongthanhdat  
I have a same problem.
If you find answer, Please tell me 😄

**Comment by MissingJade** [comment]
> Please check the README.md for the code branch for getting the network used to produce the results in the NIPS paper.

Hi, I have the same question  about weight-sharing as the first questioner, I have also check the README.md, but I still can't understand it. Could you explain it more detilely, please!

**Comment by MissingJade** [comment]
> Please check the README.md for the code branch for getting the network used to produce the results in the NIPS paper.

Hi, I have the same question  about weight-sharing as the first questioner, I have also checked the README.md, but I still can't understand it. Could you explain it more detilely, please!
