### ISSUE TITLE
Domain adaptation for day to night examples

### ISSUE THREAD

**Issue by akzaidi** [mingyuliutw/UNIT#9]
I like this paper a lot! Do you have the pretrained model or the data available for the street images/day2night examples?

**Comment by mingyuliutw** [comment]
Thanks for the nice comment! Releasing the day2night translation model or the dataset will be a very tricky task from my side. But, there is a dataset called KAIST Multispectral Pedestrian Detection Benchmark (https://sites.google.com/site/pedestrianbenchmark/). They have day-time and night-time videos for training day2night translation. It could be a good resource to get started.

**Comment by akzaidi** [comment]
Ah, okay. I'll take a look at the KAISt dataset. Thanks !
