### ISSUE TITLE
Multiple GPU training?

### ISSUE THREAD

**Issue by harsmac** [mingyuliutw/UNIT#93]
I have images with high resolution and I am running the training on GTX 1080p with 12 GB Ram. I reduced the random cropped images to 64x64 to let the training proceed. The GPU seems to run out of memory when the crop size is any greater than 64x64. Hence was wondering if it would be run on multiple GPU to speed up the training?

**Comment by mingyuliutw** [comment]
Mutliple GPU training is a bit tricky with the current implementation. Stay tuned. We plan to have a new iteration of the UNIT method, which would support multi GPU training and hopefully better quality.

**Comment by flagman** [comment]
Any update on this?

**Comment by jakubLangr** [comment]
Hi I am also wondering about the multi-GPU implementation?

**Comment by jakubLangr** [comment]
Hi @mingyuliutw I am also wondering about the multi-GPU implementation?
