### ISSUE TITLE
Organizing custom dataset for train & test

### ISSUE THREAD

**Issue by miqbal23** [mingyuliutw/UNIT#95]
Hello, 

I want to try this code on my custom dataset, and based from the [tutorial](https://github.com/mingyuliutw/UNIT/blob/master/TUTORIAL.md) I can use sample script from `gta2city` as template

But I don't know how to organize the dataset folder (eg. directory structure for each domain images). Can you show me how a proper dataset folder can be used in this code?

**Comment by mingyuliutw** [comment]
Please check `https://github.com/mingyuliutw/UNIT/tree/master/datasets/gta2city`
