### ISSUE TITLE
Strange results of examples and given trained model

### ISSUE THREAD

**Issue by mlepicka** [mingyuliutw/UNIT#97]
Hi,

I tried to recreate results for cat2tiger problem with linked on README model weights. I did everything as instructed but my results are far different from results on README 
![cat2tiger_cat0022](https://user-images.githubusercontent.com/6850881/50979690-53633900-14f7-11e9-8ce7-a2ae9238cf0a.jpg)

What could possibly go wrong?

Regards,
Marta

**Comment by mingyuliutw** [comment]
Could you share the command you use? This might have something to do with the pytorch version mismatch.
